# Generated by Django 4.1 on 2022-09-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AddField(
            model_name='design',
            name='author_name',
            field=models.CharField(default=2, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
