# Generated by Django 4.1 on 2022-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_design_options_design_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='author_name',
            field=models.CharField(default='Olga', max_length=100, verbose_name='Автор'),
        ),
    ]
