# Generated by Django 4.1 on 2022-09-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_design_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='square',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='Design_title',
            field=models.CharField(max_length=255, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='design',
            name='author_name',
            field=models.CharField(default='Olga', max_length=255, verbose_name='Автор'),
        ),
    ]
