# Generated by Django 4.1 on 2022-09-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_design_square_alter_design_design_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='square',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Площадь м2'),
        ),
    ]
