# Generated by Django 4.1 on 2022-09-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0006_alter_design_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesignRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Пойдет'), (2, 'Хорошо'), (3, 'Отлично'), (4, 'Удивительно'), (5, 'Невероятно')])),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
