# Generated by Django 4.1 on 2022-09-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0007_userdesignrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdesignrelation',
            options={'verbose_name': 'Рейтинг пользователя', 'verbose_name_plural': 'Рейтинг пользователей'},
        ),
        migrations.AddField(
            model_name='design',
            name='vieweds',
            field=models.ManyToManyField(related_name='designs', through='portfolio.UserDesignRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
