# Generated by Django 4.1 on 2022-09-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_userdesignrelation_options_design_vieweds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesignrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пойдет'), (2, 'Хорошо'), (3, 'Отлично'), (4, 'Удивительно'), (5, 'Невероятно')], null=True),
        ),
    ]
